version: '3'

volumes:
  employee_postgres_data:
    driver: local

services:
  postgres-employee:
    container_name: postgres_employee
    image: postgres:13.3
    volumes:
      - employee_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: employee
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"